name: Self-made workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: This is where you specify who to greet
        required: true
        default: World

jobs:
  greet:
    name: Greeter
    runs-on: ubuntu-latest
    steps:
      - name: Step with name
        run: echo "Hello ${{ github.event.inputs.who-to-greet }}"
      - run: |
          echo "Hello ${{ github.event.inputs.who-to-greet }}"
      - uses: RickardHF/ContainerAction@v1.0
        id: self-made-action
        name: I''ve made this
      - run: echo ${{ steps.self-made-action.outputs.greeting }}
