name: Self-made workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: This is where you specify who to greet
        required: true
        default: World

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Step with name
        run: echo "Hello ${{ github.event.inputs.who-to-greet }}"
      - run: |
          echo "Hello ${{ github.event.inputs.who-to-greet }}"
      - uses: RickardHF/ContainerAction@v1.0
        id: self-made-action
        name: I''ve made this
      - run: echo ${{ steps.self-made-action.outputs.greeting }}
  test:
    name: Testing
    needs: [build]
    environment: Test 
    runs-on: ubuntu-latest
    steps:
      - uses: RickardHF/ContainerAction@v1.0
        id: self-made-action
        with:
          who-to-greet: ${{ vars.MY_VAR }}
  staging:
    name: Staging
    runs-on: ubuntu-latest
    needs: [build]
    environment: Staging
    steps:
      - uses: RickardHF/ContainerAction@v1.0
        id: self-made-action
        with:
          who-to-greet: ${{ vars.MY_VAR }}
  production:
    name: Production
    runs-on: ubuntu-latest
    environment: Production
    needs: [test, staging]
    steps:
      - uses: RickardHF/ContainerAction@v1.0
        id: self-made-action
        with:
          who-to-greet: ${{ vars.MY_VAR }}
